In [1]:
from VRAI_multi import VRAI_multi
import pandas as pd

In [6]:
test=VRAI_multi('./test_file/')
test.file_df

,TS1,int,p1,p2,TS1_freq,int_freq,ts2a_freq,ts2b_freq
0,ol17ryu_e_int2_SSR_11_TS1.mol,ol17ryu_e_int2_SSR_6_int.mol,ol17ryu_e_int2_SSR_C_1_TS2_prod.mol,ol17ryu_e_int2_SSR_H_2_TS2_prod.mol,ol17ryu_e_int2_SSR_11_TS1.out,ol17ryu_e_int2_SSR_6_int.out,ol17ryu_e_int2_SSR_C_1_TS2.out,ol17ryu_e_int2_SSR_H_2_TS2.out
1,ol17ryu_e_int2_SSR_11_TS1.mol,ol17ryu_e_int2_SSR_6_int.mol,ol17ryu_e_int2_SSR_C_1_TS2_prod.mol,ol17ryu_e_int2_SSR_O_1_TS2_prod.mol,ol17ryu_e_int2_SSR_11_TS1.out,ol17ryu_e_int2_SSR_6_int.out,ol17ryu_e_int2_SSR_C_1_TS2.out,ol17ryu_e_int2_SSR_O_1_TS2.out
2,ol17ryu_e_int2_SSR_11_TS1.mol,ol17ryu_e_int2_SSR_6_int.mol,ol17ryu_e_int2_SSR_H_2_TS2_prod.mol,ol17ryu_e_int2_SSR_O_1_TS2_prod.mol,ol17ryu_e_int2_SSR_11_TS1.out,ol17ryu_e_int2_SSR_6_int.out,ol17ryu_e_int2_SSR_H_2_TS2.out,ol17ryu_e_int2_SSR_O_1_TS2.out

In [7]:
test.autopipe(with_spe=True)
test.processed_result_df

[16:25:26] CTAB version string invalid at line 4
[16:25:26] CTAB version string invalid at line 4
[16:25:26] CTAB version string invalid at line 4
[16:25:26] CTAB version string invalid at line 4

The higher-energy TS2 is -17.87 kJ/mol (free energy) from TS1.

**** Analysis Completed ****
Major product is ./test_file/ol17ryu_e_int2_SSR_H_2_TS2_prod.mol
Minor product is ./test_file/ol17ryu_e_int2_SSR_C_1_TS2_prod.mol

mu1_ = -0.19597356998382445
mu2_ = 0.02012571704126214
lambda1_ = 0.34524844932885496
lambda2_ = 0.37698148760467476
|g_| = 0.4499705675120856
phi = 2.3485925481176264

Product Ratio Calculation Completed:
Major Product : Minor Product ratio
98.6 : 1.4

****************************

[16:25:27] CTAB version string invalid at line 4
[16:25:27] CTAB version string invalid at line 4
[16:25:27] CTAB version string invalid at line 4
[16:25:27] CTAB version string invalid at line 4

Warning: The TS2 free energy is higher than -5 kJ/mol from TS1; TST_option = True is perferred
The higher-energy TS2 is -4.85 kJ/mol (free energy) from TS1.
TS2A_G < TS2B_G
99.48177622798057
0.5182237720194252

**** Analysis Completed ****

The difference in free energy between TS1 and TS2 is found to be less than 5 kJ/mol. The algorithm will use TST to predict the product ratios

Delta_G(INT-TS1) = -38.7 kJ/mol
Delta_G(INT-TS2A) = -20.9 kJ/mol
Delta_G(INT-TS2B) = -33.9 kJ/mol
DeltaDelta_G = 13.0 kJ/mol

Major product is ./test_file/ol17ryu_e_int2_SSR_C_1_TS2_prod.mol
Minor product is ./test_file/ol17ryu_e_int2_SSR_O_1_TS2_prod.mol

TST Major product percentage is 99.5
TST Minor product percentage is 0.5

****************************

[16:25:29] CTAB version string invalid at line 4
[16:25:29] CTAB version string invalid at line 4
[16:25:29] CTAB version string invalid at line 4
[16:25:29] CTAB version string invalid at line 4

Warning: The TS2 free energy is higher than -5 kJ/mol from TS1; TST_option = True is perferred
The higher-energy TS2 is -4.85 kJ/mol (free energy) from TS1.
TS2A_G < TS2B_G
99.92686130569946
0.07313869430053899

**** Analysis Completed ****

The difference in free energy between TS1 and TS2 is found to be less than 5 kJ/mol. The algorithm will use TST to predict the product ratios

Delta_G(INT-TS1) = -38.7 kJ/mol
Delta_G(INT-TS2A) = -16.0 kJ/mol
Delta_G(INT-TS2B) = -33.9 kJ/mol
DeltaDelta_G = 17.9 kJ/mol

Major product is ./test_file/ol17ryu_e_int2_SSR_H_2_TS2_prod.mol
Minor product is ./test_file/ol17ryu_e_int2_SSR_O_1_TS2_prod.mol

TST Major product percentage is 99.9
TST Minor product percentage is 0.1

****************************

,product,ratio,based_on,TS1_name,int_name
0,ol17ryu_e_int2_SSR_H_2_TS2_prod,98.502779,ol17ryu_e_int2_SSR_H_2_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
1,ol17ryu_e_int2_SSR_C_1_TS2_prod,1.398620,ol17ryu_e_int2_SSR_H_2_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
2,ol17ryu_e_int2_SSR_O_1_TS2_prod,0.098601,ol17ryu_e_int2_SSR_H_2_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
0,ol17ryu_e_int2_SSR_H_2_TS2_prod,98.593064,ol17ryu_e_int2_SSR_C_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
1,ol17ryu_e_int2_SSR_C_1_TS2_prod,1.399902,ol17ryu_e_int2_SSR_C_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
2,ol17ryu_e_int2_SSR_O_1_TS2_prod,0.007035,ol17ryu_e_int2_SSR_C_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
2,ol17ryu_e_int2_SSR_H_2_TS2_prod,83.319433,ol17ryu_e_int2_SSR_O_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
0,ol17ryu_e_int2_SSR_C_1_TS2_prod,16.597164,ol17ryu_e_int2_SSR_O_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
1,ol17ryu_e_int2_SSR_O_1_TS2_prod,0.083403,ol17ryu_e_int2_SSR_O_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int

In [10]:
test.raw_result_df

,TS1_name,int_name,major,minor,major_per,minor_per,TST_valid
0,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int,ol17ryu_e_int2_SSR_H_2_TS2_prod,ol17ryu_e_int2_SSR_C_1_TS2_prod,98.6,1.4,False
0,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int,ol17ryu_e_int2_SSR_C_1_TS2_prod,ol17ryu_e_int2_SSR_O_1_TS2_prod,99.5,0.5,True
0,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int,ol17ryu_e_int2_SSR_H_2_TS2_prod,ol17ryu_e_int2_SSR_O_1_TS2_prod,99.9,0.1,True

In [16]:
test2=VRAI_multi('test_file.csv')
test2.autopipe(path='./test_file/',with_spe=True)
test2.processed_result_df

[16:33:43] CTAB version string invalid at line 4
[16:33:43] CTAB version string invalid at line 4
[16:33:43] CTAB version string invalid at line 4
[16:33:43] CTAB version string invalid at line 4

The higher-energy TS2 is -17.87 kJ/mol (free energy) from TS1.

**** Analysis Completed ****
Major product is ./test_file/ol17ryu_e_int2_SSR_H_2_TS2_prod.mol
Minor product is ./test_file/ol17ryu_e_int2_SSR_C_1_TS2_prod.mol

mu1_ = -0.19597356998382445
mu2_ = 0.02012571704126214
lambda1_ = 0.34524844932885496
lambda2_ = 0.37698148760467476
|g_| = 0.4499705675120856
phi = 2.3485925481176264

Product Ratio Calculation Completed:
Major Product : Minor Product ratio
98.6 : 1.4

****************************

[16:33:45] CTAB version string invalid at line 4
[16:33:45] CTAB version string invalid at line 4
[16:33:45] CTAB version string invalid at line 4
[16:33:45] CTAB version string invalid at line 4

Warning: The TS2 free energy is higher than -5 kJ/mol from TS1; TST_option = True is perferred
The higher-energy TS2 is -4.85 kJ/mol (free energy) from TS1.
TS2A_G < TS2B_G
99.48177622798057
0.5182237720194252

**** Analysis Completed ****

The difference in free energy between TS1 and TS2 is found to be less than 5 kJ/mol. The algorithm will use TST to predict the product ratios

Delta_G(INT-TS1) = -38.7 kJ/mol
Delta_G(INT-TS2A) = -20.9 kJ/mol
Delta_G(INT-TS2B) = -33.9 kJ/mol
DeltaDelta_G = 13.0 kJ/mol

Major product is ./test_file/ol17ryu_e_int2_SSR_C_1_TS2_prod.mol
Minor product is ./test_file/ol17ryu_e_int2_SSR_O_1_TS2_prod.mol

TST Major product percentage is 99.5
TST Minor product percentage is 0.5

****************************

[16:33:46] CTAB version string invalid at line 4
[16:33:46] CTAB version string invalid at line 4
[16:33:46] CTAB version string invalid at line 4
[16:33:46] CTAB version string invalid at line 4

Warning: The TS2 free energy is higher than -5 kJ/mol from TS1; TST_option = True is perferred
The higher-energy TS2 is -4.85 kJ/mol (free energy) from TS1.
TS2A_G < TS2B_G
99.92686130569946
0.07313869430053899

**** Analysis Completed ****

The difference in free energy between TS1 and TS2 is found to be less than 5 kJ/mol. The algorithm will use TST to predict the product ratios

Delta_G(INT-TS1) = -38.7 kJ/mol
Delta_G(INT-TS2A) = -16.0 kJ/mol
Delta_G(INT-TS2B) = -33.9 kJ/mol
DeltaDelta_G = 17.9 kJ/mol

Major product is ./test_file/ol17ryu_e_int2_SSR_H_2_TS2_prod.mol
Minor product is ./test_file/ol17ryu_e_int2_SSR_O_1_TS2_prod.mol

TST Major product percentage is 99.9
TST Minor product percentage is 0.1

****************************

,product,ratio,based_on,TS1_name,int_name
0,ol17ryu_e_int2_SSR_H_2_TS2_prod,98.502779,ol17ryu_e_int2_SSR_H_2_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
1,ol17ryu_e_int2_SSR_C_1_TS2_prod,1.398620,ol17ryu_e_int2_SSR_H_2_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
2,ol17ryu_e_int2_SSR_O_1_TS2_prod,0.098601,ol17ryu_e_int2_SSR_H_2_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
0,ol17ryu_e_int2_SSR_H_2_TS2_prod,98.593064,ol17ryu_e_int2_SSR_C_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
1,ol17ryu_e_int2_SSR_C_1_TS2_prod,1.399902,ol17ryu_e_int2_SSR_C_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
2,ol17ryu_e_int2_SSR_O_1_TS2_prod,0.007035,ol17ryu_e_int2_SSR_C_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
2,ol17ryu_e_int2_SSR_H_2_TS2_prod,83.319433,ol17ryu_e_int2_SSR_O_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
0,ol17ryu_e_int2_SSR_C_1_TS2_prod,16.597164,ol17ryu_e_int2_SSR_O_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int
1,ol17ryu_e_int2_SSR_O_1_TS2_prod,0.083403,ol17ryu_e_int2_SSR_O_1_TS2_prod,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int

In [17]:
test2.raw_result_df

,TS1_name,int_name,major,minor,major_per,minor_per,TST_valid
0,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int,ol17ryu_e_int2_SSR_H_2_TS2_prod,ol17ryu_e_int2_SSR_C_1_TS2_prod,98.6,1.4,False
0,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int,ol17ryu_e_int2_SSR_C_1_TS2_prod,ol17ryu_e_int2_SSR_O_1_TS2_prod,99.5,0.5,True
0,ol17ryu_e_int2_SSR_11_TS1,ol17ryu_e_int2_SSR_6_int,ol17ryu_e_int2_SSR_H_2_TS2_prod,ol17ryu_e_int2_SSR_O_1_TS2_prod,99.9,0.1,True